### ISSUE TITLE
Design static content layout

### ISSUE THREAD

**Issue by jjlangholtz** [rubyforgood/loggerhead_shrike#5]
For non-registered users the application should provide static content outlining the significance of the Loggerhead Shrike and a call to action to signup as a Citizen Scientist. The stakeholders have suggested a few websites that can be used as inspiration:

http://www.vabci.org/golden-winged-warbler/
http://rustyblackbird.org/
http://bringbackbobwhites.org/
http://atlanticflywayshorebirds.org/

Info that should be included:
- Info about species
- Info about the working group
- What the group is trying to accomplish
- Call to action sign-up

**Comment by mobjohnson** [comment]
done
